# Generated by Django 4.2.3 on 2023-07-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
    ]
