# Generated by Django 4.2.3 on 2023-07-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_sistema_liberado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
