# Generated by Django 4.2.3 on 2023-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0003_delete_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('url_app', models.TextField(max_length=100)),
                ('icone_app', models.TextField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upfated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
