# Generated by Django 4.2.3 on 2023-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='icone_app',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='url_app',
            field=models.CharField(max_length=100),
        ),
    ]
