# Generated by Django 4.2.3 on 2023-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_sistema_icone_app_alter_sistema_url_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
    ]
