# Generated by Django 4.2.3 on 2023-07-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_remove_conta_saldo_inicial_conta_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
