# Generated by Django 4.2.3 on 2023-07-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_conta_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='saldo',
            new_name='saldo_atual',
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
