# Generated by Django 4.2.3 on 2023-07-31 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='data_pagamento',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
