# Generated by Django 4.2.3 on 2023-08-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_movimento_transferencia_alter_movimento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('debitos', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('creditos', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.conta')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
