# Generated by Django 4.2.3 on 2023-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_remove_conta_saldo_atual_remove_conta_saldo_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasaldo',
            old_name='creditos',
            new_name='despesas',
        ),
        migrations.RenameField(
            model_name='contasaldo',
            old_name='debitos',
            new_name='receitas',
        ),
        migrations.AddField(
            model_name='contasaldo',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
