# Generated by Django 4.2.3 on 2023-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_rename_creditos_contasaldo_despesas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
