# Generated by Django 4.2.3 on 2023-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_remove_movimento_transferencia_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contasaldo',
            constraint=models.UniqueConstraint(fields=('data', 'conta'), name='data_conta'),
        ),
    ]
