# Generated by Django 4.2.3 on 2023-08-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_contasaldo_data_conta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasaldo',
            options={'ordering': ['conta']},
        ),
        migrations.RemoveConstraint(
            model_name='contasaldo',
            name='data_conta',
        ),
        migrations.RemoveField(
            model_name='contasaldo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contasaldo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='contasaldo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contasaldo',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financeiro.conta'),
        ),
    ]
