# Generated by Django 4.2.3 on 2023-08-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_alter_contasaldo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasaldo',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.conta'),
        ),
    ]
