# Generated by Django 4.2.3 on 2023-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_alter_contasaldo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
