# Generated by Django 4.2.3 on 2023-08-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_conta_saldo_atual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContaSaldo',
        ),
    ]
