# Generated by Django 4.2.3 on 2023-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_delete_contasaldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
