# Generated by Django 4.2.3 on 2023-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_alter_movimento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('FX', 'Fixa'), ('VR', 'Variavel'), ('TR', 'Tranferencia')], default='VR', max_length=2),
        ),
    ]
