# Generated by Django 4.2.3 on 2023-08-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0024_alter_movimento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='financeiro.categoria'),
        ),
    ]
