# Generated by Django 4.2.3 on 2023-09-06 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0027_grupocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('RE', 'Receitas'), ('DF', 'Despesas Fixas'), ('DV', 'Despesas Variaveis'), ('DE', 'Despesas Extras'), ('DA', 'Despesas Adicionais'), ('TR', 'Tranferencia'), ('RD', 'Rendimentos')], default='DV', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='GrupoCategoria',
        ),
    ]
