# Generated by Django 4.2.3 on 2023-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0028_grupo_delete_grupocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(choices=[('RE', 'Receitas'), ('DF', 'Despesas Fixas'), ('DV', 'Despesas Variaveis'), ('DE', 'Despesas Extras'), ('DA', 'Despesas Adicionais'), ('TR', 'Tranferencia'), ('RD', 'Rendimentos')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entradas'), ('S', 'Saidas')], default='S', max_length=2),
        ),
    ]
