# Generated by Django 4.2.3 on 2023-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0029_grupo_grupo_alter_grupo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entradas'), ('S', 'Saidas')], default='S', max_length=1),
        ),
    ]
