# Generated by Django 4.2.3 on 2023-09-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0032_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='tipo_ordem',
        ),
        migrations.AddField(
            model_name='tipo',
            name='ordem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
