# Generated by Django 4.2.3 on 2023-09-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0035_remove_categoria_essencial_remove_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.tipo'),
            preserve_default=False,
        ),
    ]
