# Generated by Django 4.2.3 on 2023-09-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0036_categoria_categoria_pai_categoria_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['grupo', 'nome']},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_pai',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
