# Generated by Django 4.2.3 on 2023-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0039_alter_categoria_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='valor_planejamento',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
