# Generated by Django 4.2.3 on 2023-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0041_alter_grupo_options_remove_grupo_ordem_grupo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('I', 'Investimento'), ('S', 'Saida'), ('T', 'Tranferencia')], default='S', max_length=2),
        ),
    ]
