# Generated by Django 4.2.3 on 2024-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0043_alter_categoria_options_delete_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Investimento'), ('4', 'Tranferencia')], default='2', max_length=1),
        ),
    ]
