# Generated by Django 4.2.3 on 2024-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0045_grupo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
