# Generated by Django 4.2.3 on 2024-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0046_remove_categoria_tipo_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Receita'), ('2', 'Despesa'), ('3', 'Investimento'), ('4', 'Transferencia')], default='2', max_length=1),
        ),
    ]
