# Generated by Django 4.2.3 on 2024-01-16 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0047_categoria_tipo_alter_grupo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau1', models.SmallIntegerField()),
                ('grau2', models.SmallIntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grau1', 'grau2', 'nome'],
            },
        ),
    ]
