# Generated by Django 4.2.3 on 2024-01-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0048_planocontas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanoContas',
        ),
    ]
