# Generated by Django 4.2.3 on 2024-01-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0049_delete_planocontas'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ordem',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
