# Generated by Django 4.2.3 on 2024-01-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0050_grupo_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='essencial',
            field=models.BooleanField(default=False),
        ),
    ]
