# Generated by Django 4.2.3 on 2024-01-17 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0051_categoria_essencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='data_lancamento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
