# Generated by Django 4.2.3 on 2024-01-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0052_movimento_data_lancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-data_lancamento', '-data_vencimento', 'data_pagamento', 'tipo']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida'), ('3', 'Investimento'), ('4', 'Transferencia')], default='2', max_length=1),
        ),
    ]
