# Generated by Django 4.2.3 on 2024-01-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0053_alter_movimento_options_alter_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
